# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'i18n', :git => 'https://github.com/ruby-i18n/i18n.git', :tag => 'v1.6.0'
gem 'byebug'
