# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'faker', :git => 'https://github.com/stympy/faker.git', :tag => 'v1.9.3'
gem 'byebug'
